services:
  - type: web
    name: anonymous-feedback-system
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn feedback_system.wsgi:application"
    envVars:
      - key: RENDER
        value: true
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USE_SSL
        sync: false
