# Generated by Django 6.0.4 on 2026-05-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_alter_campusphoto_image_alter_issue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='document',
            field=models.CharField(blank=True, help_text='Path to uploaded PDF', max_length=255, null=True),
        ),
    ]
